# Generated by Django 5.0.3 on 2024-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='Hello', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
